# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for pipenv
  - package-ecosystem: "pip"
    directory: "/" # Look in the root directory
    # Check for updates daily
    schedule:
      interval: "daily"
    # Reviewers to set on update pull requests
    reviewers:
      - "CMihai99"
    # Assignees to set on update pull requests
    assignees:
      - "CMihai99"
    # Labels to set on update pull requests
    labels:
      - "dependencies"
      - "dependabot"
    # Increase the version requirements only when required
    versioning-strategy: increase-if-necessary
